import type { Metadata } from 'next';
import { siteMeta, siteUrl } from '@/config/site';

/**
 * SEO metadata foundation.
 * `defaultMetadata` is applied in the root layout; `buildMetadata` composes
 * per-page titles, descriptions, canonicals, and Open Graph/Twitter cards.
 *
 * Social cards are real PNGs generated by the `opengraph-image` routes. Next
 * only attaches a generated card to the exact segment that declares one, and a
 * page that sets `openGraph` at all suppresses even that — so the URL is named
 * explicitly here instead. Override `image` only for a genuine photograph, and
 * never with an SVG: Facebook, X, LinkedIn, WhatsApp and iMessage all refuse to
 * render one.
 */

export const defaultMetadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: `${siteMeta.name} — Immersive Pre-Owned Vehicle Showroom`,
    template: `%s | ${siteMeta.name}`,
  },
  description: siteMeta.description,
  applicationName: siteMeta.name,
  alternates: { canonical: '/' },
  openGraph: {
    type: 'website',
    siteName: siteMeta.name,
    title: `${siteMeta.name} — Immersive Pre-Owned Vehicle Showroom`,
    description: siteMeta.description,
    url: siteUrl,
    locale: 'en_CA',
  },
  twitter: {
    card: 'summary_large_image',
    title: `${siteMeta.name} — Immersive Pre-Owned Vehicle Showroom`,
    description: siteMeta.description,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, 'max-image-preview': 'large' },
  },
};

/**
 * URL of the PNG card generated for a route segment. Only segments with an
 * `opengraph-image` file have one: the site root, and each vehicle listing.
 */
export function generatedCard(path = '/'): string {
  const segment = path === '/' ? '' : path.replace(/\/$/, '');
  return `${siteUrl}${segment}/opengraph-image`;
}

interface BuildMetadataArgs {
  title: string;
  description: string;
  /** Path (e.g. "/inventory") — resolved to an absolute canonical URL. */
  path: string;
  /** A real photograph to use as the social card, overriding the generated one. */
  image?: string;
  /** Set true on interactive/utility pages that shouldn't be indexed. */
  noindex?: boolean;
  /** When true, `title` is used verbatim (skips the "%s | brand" template). */
  absoluteTitle?: boolean;
}

export function buildMetadata({
  title,
  description,
  path,
  image = generatedCard(),
  noindex = false,
  absoluteTitle = false,
}: BuildMetadataArgs): Metadata {
  const canonical = path === '/' ? '/' : path;
  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical },
    // Next replaces these objects wholesale rather than merging them into the
    // layout's defaults, so anything that should survive per-page — the card
    // type, the site name, the locale — has to be restated here. Leaving them
    // out is why every page but the root was previously serving a small
    // `summary` card with no og:type at all.
    openGraph: {
      type: 'website',
      siteName: siteMeta.name,
      locale: 'en_CA',
      title,
      description,
      url: `${siteUrl}${canonical}`,
      images: [{ url: image, width: 1200, height: 630, alt: title }],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [image],
    },
    ...(noindex ? { robots: { index: false, follow: false } } : {}),
  };
}
